import type { Metadata } from "next";
import "./globals.css";
import { readdirSync } from "fs";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = readdirSync("./app", {
    withFileTypes: true,
  })
    .filter((file) => file.isDirectory())
    .map((file) => {
      return file.name;
    });

  return (
    <html lang="en">
      <body>
        <header className="flex gap-2 px-2 py-1">
          <Link href="/" className="underline">
            Home
          </Link>
          <nav>
            <ul className="flex gap-2">
              {pages.map((page) => {
                return (
                  <li key={page} className="underline capitalize">
                    <Link href={`/${page}`}>{page}</Link>
                  </li>
                );
              })}
              <li>
                <a
                  href="https://github.com/skatingincentralpark/react-playground"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline"
                >
                  Github
                </a>
              </li>
            </ul>
          </nav>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
